version: '3.8'

services:
  backend:
    image: courseimage
    container_name: backend
    ports:
      - "8090:5051"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - networkmysql

  frontend:
    image: coursefrontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - networkmysql

networks:
  networkmysql:
    driver: bridge
